# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instaclone', '0006_auto_20201018_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pic/'),
        ),
    ]
