# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Instaclone', '0007_auto_20201018_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Instaclone.Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
