# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Instaclone', '0009_auto_20201019_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='username',
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
