# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Instaclone', '0013_auto_20201019_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='like',
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(related_name='image_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
